services:
  web:
    build: .
    ports:
      - 8000:8000
    develop:
      watch:
        - action: rebuild
          path: .
          target: /app
          ignore: _data
    environment:
      USER_AUTH_LOG_LEVEL: ${USER_AUTH_LOG_LEVEL}
      USER_AUTH_DEBUG: ${USER_AUTH_DEBUG}
      USER_AUTH_HOST: 0.0.0.0
      USER_AUTH_PORT: 8000
      USER_AUTH_API_SECRET: ${USER_AUTH_API_SECRET}
      USER_AUTH_DB_URL: ${USER_AUTH_DB_URL}
      USER_AUTH_REDIS_URL: ${USER_AUTH_REDIS_URL}
    depends_on:
      - postgres-db
      - redis-db

  postgres-db:
    image: "postgres:17"
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ${PWD}/_data/pgdata:/var/lib/pgsql/data
      - ${PWD}/_data/logs:/var/lib/pgsql/pg_wal
    environment:
      POSTGRES_USER: ${USER_AUTH_PG_USER}
      POSTGRES_PASSWORD: ${USER_AUTH_PG_PASSWORD}
      POSTGRES_DB: ${USER_AUTH_PG_DATABASE}
      PGDATA: /var/lib/pgsql/data
      POSTGRES_INITDB_WALDIR: /var/lib/pgsql/pg_wal

  redis-db:
    image: redis:8.0-rc1-alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ${PWD}/_data/redis_data:/data
    command: [ "--save", "60", "1" ]
