services:
  web:
    build: .
    ports:
      - 5000:${USER_AUTH_PORT}

  postgres-db:
    image: "postgres:17"
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ${PWD}/_data/pgdata:/var/lib/pgsql/data
      - ${PWD}/_data/logs:/var/lib/pgsql/pg_wal
    environment:
      POSTGRES_USER: ${USER_AUTH_PG_USER}
      POSTGRES_PASSWORD: ${USER_AUTH_PG_PASSWORD}
      POSTGRES_DB: ${USER_AUTH_PG_DATABASE}
      PGDATA: /var/lib/pgsql/data
      POSTGRES_INITDB_WALDIR: /var/lib/pgsql/pg_wal
